### ISSUE TITLE
FATAL EXCEPTION: java.lang.IllegalStateException (Already in the pool!)

### ISSUE THREAD

**Issue by vrishe** [codetwisted/android-widget#3]
Here's an exception:

```
java.lang.IllegalStateException: Already in the pool!  
    at android.util.Pools$SimplePool.release(Pools.java:112)  
    at android.util.Pools$SynchronizedPool.release(Pools.java:161)  
    at android.view.VelocityTracker.recycle(VelocityTracker.java:85)  
    at org.codetwisted.widget.DrawerLayout$TopDrawerImpl.handleFree(DrawerLayout.java:630)  
    at org.codetwisted.widget.DrawerLayout.onTouchEvent(DrawerLayout.java:1110)  
    ...
```

Steps to reproduce:
1. Set prolonged drawer finishnig animation duration;
2. Drag drawer to one direction;
3. During drawer being animated, catch it's handle then drag it in opposite direction;
4. (Optional) repeat starting at step 3.

**Comment by vrishe** [comment]
Have an idea on what's going on. This issue takes it's source within the `DrawerImpl#handleFree(int, int, MotionEvent)`. It happens after we try to recycle velocity tracker more than once, which happens while drawer layout stays in states other that IDLE or PULLED.

**Comment by vrishe** [comment]
55dc32878a3fe60d75e5c1bd7dad110742afa2b5 This commit contains a fix, that wipes this problem away.
